- id: '1622151365583'
  alias: Restart notification
  description: ''
  use_blueprint:
    path: gregoryduckworth/restart_notification.yaml
    input:
      notification_message: Home Assistant has succesfully restarted!
      notify_device: a52e1ff910aed3da5411cccec929a64e
- id: '1622229812148'
  alias: Turn lights out when no one is home
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '4'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.eamonn_sullivan
      state: not_home
      for:
        hours: 1
    - condition: state
      entity_id: person.theresa_sullivan
      state: not_home
      for:
        hours: 1
  action:
  - service: light.turn_off
    target:
      entity_id: light.whole_house
  mode: single
- id: '1633370443490'
  alias: Hue button pressed
  description: ''
  trigger:
  - device_id: 2341d2a8be724f4c9929d49168040eef
    domain: hue
    platform: device
    type: short_release
    subtype: 1
    unique_id: 11cf219f-1993-4926-a5c4-35e1d8067037
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.hue_button_pressed
  mode: single
- id: '1633370488207'
  alias: Hue button long pressed
  description: ''
  trigger:
  - device_id: 2341d2a8be724f4c9929d49168040eef
    domain: hue
    platform: device
    type: long_release
    subtype: 1
    unique_id: 11cf219f-1993-4926-a5c4-35e1d8067037
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.hue_button_long_pressed
  mode: single
- id: '1633450987940'
  alias: Hue dimmer pressed
  description: ''
  trigger:
  - device_id: f2944869d5973b00e81586d6bb9459e1
    domain: hue
    platform: device
    type: short_release
    subtype: 1
    unique_id: 2501805f-383c-4929-aeaf-5dedb2ea997b
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.hue_dimmer_pressed
  mode: single
- id: '1633451029488'
  alias: Hue dimmer long pressed
  description: ''
  trigger:
  - device_id: f2944869d5973b00e81586d6bb9459e1
    domain: hue
    platform: device
    type: long_release
    subtype: 1
    unique_id: 2501805f-383c-4929-aeaf-5dedb2ea997b
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.hue_dimmer_long_pressed
  mode: single
- id: '1645809702626'
  alias: Doorbell pressed
  description: ''
  trigger:
  - platform: device
    device_id: 7cd941cc659fc60f687642a70a2c82ee
    domain: shelly
    type: single
    subtype: button
  - platform: device
    device_id: 7cd941cc659fc60f687642a70a2c82ee
    domain: shelly
    type: long
    subtype: button
  - platform: device
    device_id: 7cd941cc659fc60f687642a70a2c82ee
    domain: shelly
    type: double
    subtype: button
  - platform: device
    device_id: 7cd941cc659fc60f687642a70a2c82ee
    domain: shelly
    type: triple
    subtype: button
  condition: []
  action:
  - service: script.turn_on
    data: {}
    target:
      entity_id: script.doorbell
  mode: single
- id: '1646506367466'
  alias: Motion in forest room during the day
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: f9dabd2e36ef9495f6bf99f3fac2444a
    entity_id: binary_sensor.forest_room_sensor_motion
    domain: binary_sensor
  condition:
  - condition: time
    after: 06:00:00
    before: '21:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  - condition: numeric_state
    entity_id: sensor.forest_room_lux_level
    below: '5'
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.forest_room_bright
    metadata: {}
  mode: single
- id: '1646506524009'
  alias: Turn off lights
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: f9dabd2e36ef9495f6bf99f3fac2444a
    entity_id: binary_sensor.forest_room_sensor_motion
    domain: binary_sensor
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      area_id: forest_room
  mode: single
- id: '1646506781588'
  alias: Turn on lights at night
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: f9dabd2e36ef9495f6bf99f3fac2444a
    entity_id: binary_sensor.forest_room_sensor_motion
    domain: binary_sensor
  condition:
  - condition: time
    after: '21:00:00'
    before: 06:00:00
  - type: is_illuminance
    condition: device
    device_id: f9dabd2e36ef9495f6bf99f3fac2444a
    entity_id: sensor.forest_room_sensor_luminosity
    domain: sensor
    below: 5
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.forest_room_dimmed
    metadata: {}
  mode: single
- id: '1646507246007'
  alias: Motion detected in the kitchen (day)
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 767ca4dc84f63db642c0637b2e522853
    entity_id: binary_sensor.kitchen_sensor_home_security_motion_detection
    domain: binary_sensor
  condition:
  - condition: time
    after: 06:00:00
    before: '21:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  - type: is_illuminance
    condition: device
    device_id: 767ca4dc84f63db642c0637b2e522853
    entity_id: sensor.kitchen_sensor_illuminance
    domain: sensor
    below: 10
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.kitchen_bright
    metadata: {}
  mode: single
- id: '1646507293924'
  alias: No motion for a while
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 767ca4dc84f63db642c0637b2e522853
    entity_id: binary_sensor.kitchen_sensor_home_security_motion_detection
    domain: binary_sensor
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      area_id: kitchen
  mode: single
- id: '1646507387795'
  alias: Motion detected at night
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 767ca4dc84f63db642c0637b2e522853
    entity_id: binary_sensor.kitchen_sensor_home_security_motion_detection
    domain: binary_sensor
  condition:
  - condition: time
    after: '21:00:00'
    before: 06:00:00
    weekday:
    - sun
    - sat
    - fri
    - thu
    - wed
    - tue
    - mon
  - condition: numeric_state
    entity_id: sensor.kitchen_sensor_illuminance
    below: '10'
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.kitchen_dimmed
    metadata: {}
  mode: single
