- id: '1621929058456'
  alias: Turns lights on as the sun sets
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:45
  condition: []
  action:
  - service: light.turn_on
    target:
      area_id: living_room
    data:
      profile: Bright
  - service: light.turn_on
    target:
      area_id: sun_room
    data:
      profile: Relax
  mode: single
