- id: '1622151365583'
  alias: Restart notification
  description: ''
  use_blueprint:
    path: gregoryduckworth/restart_notification.yaml
    input:
      notification_message: Home Assistant has succesfully restarted!
      notify_device: a52e1ff910aed3da5411cccec929a64e
- id: '1622229812148'
  alias: Turn lights out when no one is home
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '4'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.eamonn_sullivan
      state: not_home
      for:
        hours: 1
    - condition: state
      entity_id: person.theresa_sullivan
      state: not_home
      for:
        hours: 1
  action:
  - service: light.turn_off
    target:
      entity_id: light.whole_house
  mode: single
- id: '1633370443490'
  alias: Hue button pressed
  description: ''
  trigger:
  - device_id: 2341d2a8be724f4c9929d49168040eef
    domain: hue
    platform: device
    type: short_release
    subtype: 1
    unique_id: 11cf219f-1993-4926-a5c4-35e1d8067037
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.hue_button_pressed
  mode: single
- id: '1633370488207'
  alias: Hue button long pressed
  description: ''
  trigger:
  - device_id: 2341d2a8be724f4c9929d49168040eef
    domain: hue
    platform: device
    type: long_release
    subtype: 1
    unique_id: 11cf219f-1993-4926-a5c4-35e1d8067037
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.hue_button_long_pressed
  mode: single
- id: '1633450987940'
  alias: Hue dimmer pressed
  description: ''
  trigger:
  - device_id: f2944869d5973b00e81586d6bb9459e1
    domain: hue
    platform: device
    type: short_release
    subtype: 1
    unique_id: 2501805f-383c-4929-aeaf-5dedb2ea997b
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.hue_dimmer_pressed
  mode: single
- id: '1633451029488'
  alias: Hue dimmer long pressed
  description: ''
  trigger:
  - device_id: f2944869d5973b00e81586d6bb9459e1
    domain: hue
    platform: device
    type: long_release
    subtype: 1
    unique_id: 2501805f-383c-4929-aeaf-5dedb2ea997b
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.hue_dimmer_long_pressed
  mode: single
