- id: '1621929058456'
  alias: Turns lights on as the sun sets
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '10'
  condition: []
  action:
  - service: light.turn_on
    target:
      area_id:
      - living_room
      - sun_room
    data:
      transition: 180
      profile: Bright
      brightness_pct: 100
  mode: single
- id: '1622102535373'
  alias: Turn off Eamonn's office
  description: ''
  trigger:
  - platform: time
    at: '23:30'
  condition:
  - condition: state
    entity_id: switch.tapo_smart_plug
    state: 'on'
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.tapo_smart_plug
  mode: single
- id: '1622102608384'
  alias: Turn on Eamonn's office
  description: ''
  trigger:
  - platform: time
    at: 07:00
  condition:
  - condition: state
    entity_id: switch.tapo_smart_plug
    state: 'off'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.tapo_smart_plug
  mode: single
- id: '1622115257554'
  alias: Turn on hallway lights on arrival
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.theresa_sullivan_s_iphone
    - device_tracker.theresansiphone
    - device_tracker.theresansiphone_2
    - device_tracker.eamonns_iphone
    - device_tracker.eamonns_iphone_2
    from: not_home
    to: home
  condition:
  - condition: numeric_state
    entity_id: sun.sun
    below: '5'
    attribute: elevation
  action:
  - service: light.turn_on
    target:
      entity_id: light.hallway
    data:
      transition: 30
      profile: Bright
      brightness_pct: 100
  mode: single
- id: '1622116981249'
  alias: Turn off dryer
  description: ''
  trigger:
  - platform: time
    at: '23:00'
  condition: []
  action:
  - type: turn_off
    device_id: 5d535feaa18a826d4c342ff691da2893
    entity_id: switch.bf951383374722a8b32y7i
    domain: switch
  mode: single
- id: '1622117034746'
  alias: Turn on dryer
  description: ''
  trigger:
  - platform: time
    at: 05:00
  condition: []
  action:
  - type: turn_on
    device_id: 5d535feaa18a826d4c342ff691da2893
    entity_id: switch.bf951383374722a8b32y7i
    domain: switch
  mode: single
- id: '1622129247773'
  alias: Eamonn has left the building
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.eamonn_sullivan
      zone_entity: zone.home
      notify_device: a52e1ff910aed3da5411cccec929a64e
- id: '1622151365583'
  alias: Restart notification
  description: ''
  use_blueprint:
    path: gregoryduckworth/restart_notification.yaml
    input:
      notification_message: Home Assistant has succesfully restarted!
      notify_device: a52e1ff910aed3da5411cccec929a64e
