- id: '1622151365583'
  alias: Restart notification
  description: ''
  use_blueprint:
    path: gregoryduckworth/restart_notification.yaml
    input:
      notification_message: Home Assistant has succesfully restarted!
      notify_device: a52e1ff910aed3da5411cccec929a64e
- id: '1622229812148'
  alias: Turn lights out when no one is home
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '4'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.eamonn_sullivan
      state: not_home
      for:
        hours: 1
    - condition: state
      entity_id: person.theresa_sullivan
      state: not_home
      for:
        hours: 1
  action:
  - service: light.turn_off
    target:
      entity_id: light.whole_house
  mode: single
