
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
    - type: homeassistant

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

media_player:
  - platform: soundtouch
    host: 192.168.1.201
    port: 8090
    name: Soundtouch Living Room
  - platform: soundtouch
    host: 192.168.1.202
    port: 8090
    name: Soundtouch Kitchen

spotify:
  client_id: 0185bb658f774eb2b288e43c978c8ba1
  client_secret: !secret spotify_secret

device_tracker:
  - platform: netgear
    password: !secret router_password
    new_device_defaults:
      track_new_devices: true

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: processor_temperature
      - type: memory_use_percent
      - type: processor_use
      - type: ipv4_address
        arg: wlan0
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

mqtt:
  broker: localhost

switch:
    platform: tapo_p100_control
    ip_address: 192.168.1.204
    email: eamonn.sullivan@gmail.com
    password: !secret tplink_password
